#ifndef HANDSHAKE_WITH_PEER_H
#define HANDSHAKE_WITH_PEER_H

#include <stdint.h>
#include <stddef.h>
#include "contact_tracker.h"
#include "torrent_parser.h"
#define PSTR_LEN        19
#define HANDSHAKE_LEN   68
#define PROTOCOL_STRING "BitTorrent protocol"
#define TIMEOUT_SECONDS 5





/**
 * Connects to a peer using TCP and performs the BitTorrent handshake.
 *
 * @param peer       Pointer to Peer struct containing IP + port.
 * @param info_hash  20-byte torrent info_hash.
 * @param client_id  20-byte peer_id generated by your client.
 *
 * @return socket descriptor on success (>=0),
 *         -1 on failure.
 *
 * If successful, the returned socket fd is ready for sending/receiving
 * standard BitTorrent protocol messages (bitfield, interested, request, etc).
 */
int connect_and_handshake(Peer *peer, const unsigned char *info_hash, const unsigned char *client_id);

/*
* Safely receives the bytes from the peer. If successful receives n_bytes, it returns n bytes else returns that error occurred (-1)
* or that the connection was closed */


int safe_recv(int sock_fd,unsigned char *buffer, size_t n_bytes);
int recv_handshake(int fd, TorrentState *ts);

#endif  // CONTACT_PEER_H
